### ISSUE TITLE
Alternative functions to follow multiple requests (cursors)

### ISSUE THREAD

**Issue by jdub** [jdub/node-twitter#14]
Pretty much everything using _getUsingCursor should not do so by default, but there should be a standard suffix or method for making them do so.

**Comment by dougalcampbell** [comment]
I've been toying with some methods of my own for getting all friends/followers without using _getUsingCursor to grab everything in a solid chunk. The main problem for me was tracking when all of the data packets have been retrieved. I wound up setting a special result condition containing the expected packet count, passing that back to the client (browser-end javascript code, not the twitter client code on the node-end), and then letting the client end detect when the number of received packets matched the expected packet count. 

But this was just a kludge so that I could get my prototype up quickly. It really needs an internal "black box" implementation inside of node-twitter.

I can give you my Twitter.getAllFollowers() / Twitter.getAllFriends() code, but I feel like it's less than optimal.
